package com.iot.case2;

import com.firebase.patch.PatchToMyHouse;

public class CaseJFrame extends javax.swing.JFrame {
    private boolean focusGained = false;
    // 接收 Arduino 的資料 
    private Callback callback = new Callback() {
        @Override
        public void getValue(String fulldata) {
            // 檢查資料是否有包含 #
            if(!fulldata.contains("#")) {
                return;
            }
            // 去除 #
            fulldata = fulldata.replaceAll("#", "");
            // 切割資料
            String[] array = fulldata.split(",");
            // 切割後資料欄位數
            //System.out.println(array.length);
            // 確認合法資料欄位數 (假設=7)
            if(array.length != 7){
                return;
            }
            comNumber.setEnabled(false);
            startBtn.setEnabled(false);
            // 分析資料
            System.out.printf("溫度: %s 濕度: %s cds: %s led: %s 距離: %s pm2.5: %s servoDegree: %s\n", array[0], array[1], array[2], array[3], array[4], array[5], array[6]);
            temp.setText(array[0]);
            humd.setText(array[1]);
            cdsValue.setText(array[2]);
            ledOnOff.setText(array[3].equals("1")?"On":"Off");
            distance.setText(array[4]);
            pm25.setText(array[5]);
            
            // 上傳資料
            PatchToMyHouse.patch("myhouse", array[0], array[1], array[2], array[3], array[4], array[5], array[6]);
            // 取得MyHouse資料
            String open = PatchToMyHouse.get("myhouse", "open");
            if(open.equals("1")) {
                // 開門
                callback.setRelayValue(true);
                PatchToMyHouse.set("myhouse", "open", 0);
            }
            // 取得RFID資料
            if(!focusGained) {
                passNumber.setText(PatchToMyHouse.get("rfid", "passNumber"));
                balance.setText(PatchToMyHouse.get("rfid", "balance"));
                number.setText(PatchToMyHouse.get("rfid", "number"));
            }
        }
    };
    
    public CaseJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        humd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cdsValue = new javax.swing.JLabel();
        distance = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        pm25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ledOnOff = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        comNumber = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passNumber = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        number = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartHome");

        temp.setBackground(new java.awt.Color(0, 153, 153));
        temp.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        temp.setText("00.00");

        jLabel2.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        jLabel2.setText("°C");

        humd.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        humd.setText("00.00");

        jLabel4.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        jLabel4.setText("%");

        cdsValue.setFont(new java.awt.Font("Gabriola", 0, 48)); // NOI18N
        cdsValue.setText("0.00");

        distance.setFont(new java.awt.Font("Gabriola", 0, 48)); // NOI18N
        distance.setText("000");

        label5.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        label5.setText("PM2.5");

        pm25.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        pm25.setText("A");

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jButton1.setText("OpenCloce");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ledOnOff.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        ledOnOff.setText("0");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setText("cm");

        startBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        startBtn.setText("Start");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        comNumber.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        comNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6", "7", "8", "9", "10" }));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("COM");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("RFID");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("PassNumber: ");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Balance: ");

        passNumber.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        passNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passNumber.setText("0");
        passNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passNumberFocusLost(evt);
            }
        });

        balance.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        balance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        balance.setText("0");
        balance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                balanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                balanceFocusLost(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pm25))
                            .addComponent(temp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(distance)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cdsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ledOnOff)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(humd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(balance, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(passNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addComponent(number))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startBtn)
                            .addComponent(comNumber)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(temp)
                                    .addComponent(jLabel2)
                                    .addComponent(humd)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cdsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ledOnOff))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(distance)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label5)
                                    .addComponent(pm25))))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(passNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        try {
            (new TwoWaySerialComm(callback)).connect("COM" + comNumber.getSelectedItem().toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_startBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        callback.setRelayValue(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PatchToMyHouse.set("rfid", "passNumber", Integer.parseInt(passNumber.getText()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PatchToMyHouse.set("rfid", "balance", Integer.parseInt(balance.getText()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void passNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passNumberFocusGained
        focusGained = true;
    }//GEN-LAST:event_passNumberFocusGained

    private void passNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passNumberFocusLost
        focusGained = false;
    }//GEN-LAST:event_passNumberFocusLost

    private void balanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_balanceFocusGained
        focusGained = true;
    }//GEN-LAST:event_balanceFocusGained

    private void balanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_balanceFocusLost
        focusGained = false;
    }//GEN-LAST:event_balanceFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaseJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JLabel cdsValue;
    private javax.swing.JComboBox<String> comNumber;
    private javax.swing.JLabel distance;
    private javax.swing.JLabel humd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel ledOnOff;
    private javax.swing.JTextField number;
    private javax.swing.JTextField passNumber;
    private javax.swing.JLabel pm25;
    private javax.swing.JButton startBtn;
    private javax.swing.JLabel temp;
    // End of variables declaration//GEN-END:variables
}
